export default {
  REQUEST_START: 'REQUEST_START',
  REQUEST_DONE: 'REQUEST_DONE',
  ADD_DATA: 'ADD_DATA',
  SEARCH_REQUEST_START: 'SEARCH_REQUEST_START',
  SEARCH_ADD_IMAGES: 'SEARCH_ADD_IMAGES',
  SEARCH_REQUEST_DONE: 'SEARCH_REQUEST_DONE',
  SEARCH_UPDATE_VALUE: 'SEARCH_UPDATE_VALUE'
};
